package com.c1837njavareact.backend.model.enums;

public enum ProyectoRole {
  OWNER,
  FRONTEND,
  BACKEND,
  UX_UI,
  DEVOPS,
  QA,
  PRODUCT_MANAGER,
  CLOUD_ARCHITECT,
  DATA_ANALYST,
  MACHINE_LEARNING,
  SECURITY_ANALYST,
  NETWORK_ENGINEER,
  SYSTEMS_ADMINISTRATOR,
  DATABASE_ADMINISTRATOR,
  FULLSTACK_DEVELOPER,
  MOBILE_DEVELOPER,
  GAME_DEVELOPER,
  CYBERSECURITY,
  OTHER
}
