spring:
  application:
    name: backend
  datasource:
#    url: jdbc:postgresql://dpg-cpf4i6f109ks73bditq0-a.oregon-postgres.render.com:5432/mydatabase_u3j7
#    userName: myuser
#    password: PkBdLl12BX39MhbsD1G9xTnvS24EohKA
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
jwt:
  secret: ${SECRET_KEY}
  expirationTime: 1440000
api:
  base-path: api/v1
logging:
  level:
    org:
      springframework:
        security: DEBUG