spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://db:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true