spring:
  application:
    name: backend
  datasource:
    url: ${URL_DATABASE}
    userName: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
jwt:
  secret: ${SECRET_KEY}
  expirationTime: 86400000
api:
  base-path: api/v1